inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/*
    - spec/**/*

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 40

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'app/controllers/home_controller.rb'

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/meal_tasks_controller.rb'
    - 'app/controllers/tasks_controller.rb'


Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RedundantSelf:
  Exclude:
    - 'app/models/meal_task.rb'
    - 'app/models/task.rb'
    - 'app/models/user.rb'

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 200

Lint/UselessAssignment:
  Exclude:
    - 'app/controllers/application_controller.rb'
